server:
  port: 8081
  servlet:
    context-path: /algeria-cities
spring:
  application:
    name: algeria-cities
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  profiles:
    active: uat