server:
  port: 8081
  adhan:
    api:
      url: https://api.aladhan.com/v1/timingsByCity/
  servlet:
    context-path: /algeria-cities
spring:
  application:
    name: algeria-cities
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
        format_sql: true
    defer-datasource-initialization: true
  profiles:
    active: uat
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
#### Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always


